name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Clean with Maven
      run: mvn clean 
    - name: Compile with Maven
      run: mvn compile 
    - name: Build with Maven
      run: mvn package 
    - name: Test with Maven
      run: mvn test 
